### ISSUE TITLE
Passage à IRC

### ISSUE THREAD

**Issue by Matyu9** [Cantina-Org/Hermes#11]

**Comment by Matyu9** [comment]
C’est pas sur mais y’a des chances

**Comment by Matyu9** [comment]
Il faut juste que je regarde si on peut faire des messages persistant

**Comment by Timtonix** [comment]
À mon avis, c'est pas une si bonne idée que ça finalement, vu que rien est persistant...

**Comment by Matyu9** [comment]
Je suis en train de regarder apparemment il y a des serveurs IRC qui savent les messages

**Comment by Matyu9** [comment]
Fermeture de l'issue car les avantages ont été recréé avec notre système.
